feat: creates for configured regions delta changes
MapColonies/cosmocrat pull request #1
Opened 2020-12-03 15:25 UTC by melancholiai

2020-12-03 15:36 UTC, syncush requested changes

2020-12-03 15:36 UTC, syncush commented on src/config.py
> +OSMCONVERT_PATH='/home/amito/src/osmconvert/osmconvert'
there are values specified to your pc, should from env

2020-12-03 15:36 UTC, syncush commented on src/helper_functions.py
> +#     return remove_dots_from_edges_of_string(result)
remove if unneccesary

2020-12-03 15:36 UTC, syncush commented on src/start.py
> +    israel = Region(name='Israel', polygon=israel_polygon, interval=3600, sub_regions=[tel_aviv, jerusalem])
should read a config and allocate the variables dynamically

2020-12-10 16:07 UTC, melancholiai commented
definition of done has changed.
a new pull request has been opened: https://github.com/MapColonies/cosmocrat/pull/2

2020-12-10 16:07 UTC, closed without merging